name: Deploy to SiteGround

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (adjust as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Store this as a GitHub secret

      - name: Deploy files via rsync
        run: |
          rsync -avz --delete-after \
          -e "ssh -p 18765 StrictHostKeyChecking=no" \
          ./ u2709-o8dmz8qkmjz9@andyc175.sg-host.com:/home/customer/www/andyc175.sg-host.com/public_html/
