name: Deploy to SiteGround

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start SSH Agent and Add SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH Connection (No Passphrase)
        run: |
          ssh -o StrictHostKeyChecking=no -p 18765 u1034-ybifkcyw3x5g@ssh.bsl-assist.co.uk \
          'echo "SSH connection successful!"' || { echo "SSH connection failed"; exit 1; }

      - name: Deploy files via rsync
        run: |
          rsync -avz \
          -e "ssh -p 18765 -o StrictHostKeyChecking=no" \
          ./ u1034-ybifkcyw3x5g@ssh.bsl-assist.co.uk:/home/customer/www/bsl-assist.co.uk/public_html/ || { echo "Rsync failed"; exit 1; }
