name: Deploy to SiteGround

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (adjust as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          sshpass -p "${{ secrets.SSH_PASSPHRASE }}" ssh-add private_key

      - name: Deploy files via rsync
        run: |
          rsync -avz --delete-after \
          -e "ssh -p 18765 -o StrictHostKeyChecking=no" \
          ./ u2709-o8dmz8qkmjz9@ssh.andyc175.sg-host.com:/home/customer/www/andyc175.sg-host.com/public_html/
